apiVersion: v1
kind: Service
metadata:
  name: nginx
  # servicer labels
  # labels:
  #   app: nginx
  #   version: blue
spec:
  type: LoadBalancer
  # Service uses the below labels to select the pods
  selector:
    app: nginx
    version: blue
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port