apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-blue
  labels:
    version: blue
    app: nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      version: blue
      app: nginx
  # Pod
  template:
    metadata:
      labels:
        version: blue
        app: nginx
    spec:
      containers:
      - name: nginx
        image: venkey57/blue-green:0.2.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---