# A Service never checks the top-level Deployment metadata.labels. It only checks the Pod's labels defined under spec.template.metadata.labels.

apiVersion: v1
kind: Service
metadata:
  name: nginx-preview
  # servicer labels
  # labels:
  #   app: nginx
  #   version: blue
spec:
  type: LoadBalancer
  # Service uses the below labels to select the pods
  selector:
    app: nginx
    version: green
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port


# Switch Live Traffic from blue to Green (Instant Cutover)
# kubectl patch svc nginx -p '{"spec":{"selector":{"version":"green"}}}'

# Tear Down / Scale Down the Blue Environment (Cleanup), all blu pods will goes down , just making replicas 0, nothing will happen to delpoyment
#kubectl patch deployment nginx-blue -p '{"spec":{"replicas":0}}'

# devops